%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-raspimouse-slam
Version:        3.0.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS raspimouse_slam package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jazzy-hls-lfcd-lds-driver
Requires:       ros-jazzy-joint-state-publisher
Requires:       ros-jazzy-joy-linux
Requires:       ros-jazzy-nav2-map-server
Requires:       ros-jazzy-raspimouse
Requires:       ros-jazzy-raspimouse-description
Requires:       ros-jazzy-raspimouse-ros2-examples
Requires:       ros-jazzy-robot-state-publisher
Requires:       ros-jazzy-rplidar-ros
Requires:       ros-jazzy-rviz2
Requires:       ros-jazzy-slam-toolbox
Requires:       ros-jazzy-urg-node
Requires:       ros-jazzy-xacro
Requires:       ros-jazzy-ros-workspace
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-hls-lfcd-lds-driver
BuildRequires:  ros-jazzy-joint-state-publisher
BuildRequires:  ros-jazzy-joy-linux
BuildRequires:  ros-jazzy-nav2-map-server
BuildRequires:  ros-jazzy-raspimouse
BuildRequires:  ros-jazzy-raspimouse-description
BuildRequires:  ros-jazzy-raspimouse-ros2-examples
BuildRequires:  ros-jazzy-robot-state-publisher
BuildRequires:  ros-jazzy-rplidar-ros
BuildRequires:  ros-jazzy-rviz2
BuildRequires:  ros-jazzy-slam-toolbox
BuildRequires:  ros-jazzy-urg-node
BuildRequires:  ros-jazzy-xacro
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-jazzy-ament-lint-auto
BuildRequires:  ros-jazzy-ament-lint-common
%endif

%description
SLAM package for Raspberry Pi Mouse

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Mon Dec 02 2024 RT Corporation <shop@rt-net.jp> - 3.0.0-1
- Autogenerated by Bloom

